### ISSUE TITLE
Scientifica

### ISSUE THREAD

**Issue by gastrodon** [masaeedu/bitmap-fonts#1]
Why was scientifica removed?

**Comment by masaeedu** [comment]
@gastrodon Sorry, in case this wasn't clear this isn't my repo, it's just a copy I uploaded off my laptop so I can share dotfiles (i don't remember how I cloned it there). You can see the actual repo here: https://github.com/Tecate/bitmap-fonts

**Comment by masaeedu** [comment]
Scientifica was removed because I started fetching it via Nix (but again, this isn't something you need to care about, because this repo is just a dump of something I use for my dotfiles, see link above for the actual repo).

**Comment by gastrodon** [comment]
Oh, thanks for the info. I wasn't aware of the other repo
